export {addCategoriaFactory} from '../factories/Categoria/addCategoriaFactory'
export {addPhotoFactory} from '../factories/Photo/addPhotoFactory'
export {ListCategoriaFactory} from '../factories/Categoria/listCategoriaFactory'
export {updateCategoriaFactory} from '../factories/Categoria/updateCategoriaFactory'
export { deleteCategoriaFactory } from '../factories/Categoria/deleteCategoriaFactory'
export { deletePhotoFactory } from '../factories/Photo/deletePhotoFactory'
export { ListPhotoFactory } from '../factories/Photo/listPhotoFactory'
export {getPhotoFactory} from '../factories/Photo/getPhotoFactory'
export { addProdutoFactory } from '../factories/Produto/addProdutoFactory'
export {listProdutoFactory} from '../factories/Produto/listProdutoFactory'
export {ListProdutoCategoriaFactory} from '../factories/Produto/listProdutoCategoriaFactory'
export {getProdutoFactory} from '../factories/Produto/getProdutoFactory'
export {updateProdutoFactory} from '../factories/Produto/updateProdutoFactory'
export {deleteProdutoFactory} from '../factories/Produto/deleteProdutoFactory'
export {addEstoqueFactory} from '../factories/Estoque/addEstoqueFactory'
export {checkAvailableFactory} from '../factories/Estoque/checkAvailableFactory'
export {removeEstoqueFactory} from '../factories/Estoque/removeEstoqueFactory'
export {countEstoqueFactory} from '../factories/Estoque/countEstoqueFactory'
 